### ISSUE TITLE
Fix image options type

### ISSUE THREAD

**Issue by clabe45** [etro-js/etro#116]
In [line 4](https://github.com/clabe45/vidar/blob/master/src/layer/image.ts#L4) of **image.ts**, the type `ImageOptions` is set to be the same as `VisualOptions`, when it really should be the same as `VisualSourceOptions`. `VisualSourceOptions` includes necessary fields for visual layers with an HTML element as its source. We just need to use this type instead of `VisualOptions`.

**Comment by eyuelberga** [comment]
I would like to help out with this
