### ISSUE TITLE
Can't find AudioContext

### ISSUE THREAD

**Issue by Enzo-bianchi** [etro-js/etro#121]
Hello,
I'm trying to use your library with Ionic and Capacitor, but on the iOS simulator, I have this error :

`ReferenceError: Can't find variable: AudioContext`

I tried to pass the audioContext, but without success
![image](https://user-images.githubusercontent.com/9719937/156834138-117f24fd-dbea-4bcc-8b25-66c0ea6ce364.png)

<img width="602" alt="image" src="https://user-images.githubusercontent.com/9719937/156834266-22ab1118-8a49-4cc8-9da6-f32caab8b165.png">

However, the AudioContext seems defined, so I don't understand why I get this error :( 
Maybe is not compatible at all ? I didn't tried on Android for now

**Comment by clabe45** [comment]
Hi, I think this has happened on Safari before. Are you using etro 0.8.x?

**Comment by Enzo-bianchi** [comment]
Yes, I use the 0.8.4 version

**Comment by clabe45** [comment]
Hmm, can you expand the stacktrace? Also, does the same error occur if you run `new context()` before you create the movie?

**Comment by Enzo-bianchi** [comment]
Ok I think I found the Issue :
Into movie.ts :  the `getDefaultOptions`  method

`_actx: new AudioContext()`

I tried to put it, `undefined` and the object movie is working now with my AudioContext on the simulator

But I have another issue, I put two ImageLayer and  after the first photo

<img width="557" alt="image" src="https://user-images.githubusercontent.com/9719937/156895173-24e50e30-62ee-43d9-ace8-2727cc467e7f.png">

<img width="582" alt="image" src="https://user-images.githubusercontent.com/9719937/156895200-d5a217b7-10c7-4060-951e-c9d579caaaf2.png">


<img width="480" alt="image" src="https://user-images.githubusercontent.com/9719937/156895124-6a442343-fd22-4de1-b77f-037264ecb4cd.png">

If I put autoRefrsh at false i don't have the error but it doesn't go on the second layer

**Comment by clabe45** [comment]
Ok, thanks. The first issue should be fixed now.

Interesting, do you mind opening a new issue for the second problem? Those details are really helpful but please add your code too.
