### ISSUE TITLE
Maximum call stack size exceeded on refresh

### ISSUE THREAD

**Issue by Enzo-bianchi** [etro-js/etro#124]
Hi,
I found an infinite loop on the refresh method, I added only  image layer based on the selected image in the gallery,  and when I play the video, after the first layer, I think the refresh is executed and crash 

```
prepare() {
    this.images.forEach(i => {
      this.imgContainer.nativeElement.src = i.webPath
      var imageLayer = new etro.layer.Image({ startTime: this.images.indexOf(i), duration: 1, source: this.imgContainer.nativeElement })
      this.movie.addLayer(imageLayer)
    })
  }
  play() {
      this.movie.play()
  }
```

<img width="557" alt="image" src="https://user-images.githubusercontent.com/9719937/156895173-24e50e30-62ee-43d9-ace8-2727cc467e7f.png">

<img width="582" alt="image" src="https://user-images.githubusercontent.com/9719937/156895200-d5a217b7-10c7-4060-951e-c9d579caaaf2.png">

<img width="541" alt="image" src="https://user-images.githubusercontent.com/9719937/156943955-4abf6f5d-9e8d-40c5-aead-bb54dc9c346b.png">

![image](https://user-images.githubusercontent.com/9719937/156944399-9ddffe80-1438-438a-8be9-ead6e015d55e.png)

If I put autoRefresh at false I don't have the error but it doesn't go on the second layer,
The error is on simulator and web

**Comment by clabe45** [comment]
[Removing auto-refresh](#130) will solve this problem (along with many, many others). In the meantime, the fix is to add `'active'` to `etro.effect.Base#publicExcludes`.
