### ISSUE TITLE
Redeclare `source` as an `HTMLAudioElement` in `Audio`

### ISSUE THREAD

**Issue by clabe45** [etro-js/etro#167]

**Comment by KidesLeo** [comment]
Is this in the audio-source type definitions?

**Comment by clabe45** [comment]
@KidesLeo it's in src/layer/audio.ts . The task is to declare `source` as the new type in this class.

**Comment by clabe45** [comment]
I overlooked something when reviewing the PR - `source` is supposed to be updated in `Audio` not `AudioSource`. Re-opening the issue for anyone to do
