### ISSUE TITLE
Custom duration for `play()`

### ISSUE THREAD

**Issue by clabe45** [etro-js/etro#181]

**Comment by clabe45** [comment]
Hey, yes to both. It would be a `number` in seconds, and it would stop after that many seconds passes. The `record` function already supports a `duration`, you can use that for reference.

**Comment by clabe45** [comment]
Yeah, move the assignment from `stream` to `play` (`stream` calls `play`)

**Comment by leanjunio** [comment]
I have https://github.com/etro-js/etro/pull/208 for this
