### ISSUE TITLE
Only stop layers when they're active

### ISSUE THREAD

**Issue by clabe45** [etro-js/etro#189]
In `Movie#pause`, add a check to only stop a layer if its `active` property is set to true.

**Comment by leanjunio** [comment]
Does this suffice @clabe45 ?
```ts
pause (): Movie {
    // Update state
    this._paused = true

    // Deactivate all layers
    for (let i = 0; i < this.layers.length; i++) {
      if (Object.prototype.hasOwnProperty.call(this.layers, i)) {
        const layer = this.layers[i]
       
        if (layer.active) {
          layer.stop()
          layer.active = false
        }
      }
    }

    // For backwards compatibility, notify event listeners that the movie has
    // paused
    publish(this, 'movie.pause', {})

    return this
  }
```

**Comment by clabe45** [comment]
Thanks for contributing, looks great! Send the PR along and I'll review it

**Comment by leanjunio** [comment]
Created https://github.com/etro-js/etro/pull/201 for this issue

**Comment by leanjunio** [comment]
@clabe45 hope you don't mind but I was having some issues with the rebasing of previous commits so I just opened up a new PR for the canvas dependency error. Do you want to get that merged first before I create a PR for the actual stop layer logic changes?

**Comment by clabe45** [comment]
Hi @leanjunio, thank you! I just merged it

**Comment by leanjunio** [comment]
@clabe45 sweet! I'll open up one for the actual changes for the current issue

**Comment by leanjunio** [comment]
Created one for the current issue: https://github.com/etro-js/etro/pull/203

**Comment by clabe45** [comment]
Merged! I'll credit you to the release notes of the upcoming minor release

**Comment by leanjunio** [comment]
> 

awesome, thanks @clabe45!
