### ISSUE TITLE
Make `Movie._whenReady` private

### ISSUE THREAD

**Issue by clabe45** [etro-js/etro#193]

**Comment by HalfToothed** [comment]
hey @clabe45 i want to work on this issue can you assign it to me and give some description about it

**Comment by clabe45** [comment]
Hey, the task is to make the `_whenReady` method in src/movie/movie.ts private. Feel free to send over any questions

**Comment by clabe45** [comment]
Unassigning if anyone else wants to try

**Comment by leanjunio** [comment]
@clabe45 I can take this on

**Comment by leanjunio** [comment]
I have https://github.com/etro-js/etro/pull/204
