### ISSUE TITLE
Replace discord link with badge

### ISSUE THREAD

**Issue by clabe45** [etro-js/etro#223]

**Comment by viktoriussuwandi** [comment]
Hi [clabe45](https://github.com/clabe45),

May I try to help on this issue ?

If yes,
which style you prefer, how about this ![Discord](https://img.shields.io/badge/Discord-%235865F2.svg?style=for-the-badge&logo=discord&logoColor=white) ?

**Comment by clabe45** [comment]
Hi, thanks for contributing! That style is fine. I'll merge a PR if you want to open one
