### ISSUE TITLE
Add `onDraw` option to `Movie.play()`

### ISSUE THREAD

**Issue by clabe45** [etro-js/etro#230]
This optional user-provided callback should run at the end of every call to `Movie._render()`

**Comment by abidjappie** [comment]
Please let have a look, and let me know there's anything I need to change.
It's a bit `nitpick` but do you have any preference for the order of options?

https://github.com/etro-js/etro/pull/266/files#diff-64b537ef6c10478f473ee89b6884594c5c71545b1989d55aca63f3b08639ded1R133-R135

e.g `method-alphabetical`, `value-alphabetical` or `all-alphabetical`

**Comment by clabe45** [comment]
Not sure what each of those ordering schemes mean, but how you have it in the PR is fine. Which one would you suggest using in the future? You are I can maybe update the contributing guide
