### ISSUE TITLE
Can't add an outline to a text layer

### ISSUE THREAD

**Issue by Alkondr223322** [etro-js/etro#236]
### Discussed in https://github.com/etro-js/etro/discussions/234

<div type='discussions-op-text'>

<sup>Originally posted by **Alkondr223322** August  5, 2023</sup>
Hi, I'm looking for a way to add an outline to the text in the Movie to make it more visible

`    const textLayer = new etro.layer.Text({ 

      startTime: startTime, 
      
      duration: durationStep, 
      
      text: sentence, 
      
      // x: 0, // default: 0 
      
      // y: 0, // default: 0 
      
      // width: 400, // default: null (full width) 
      
      // height: 400, // default: null (full height) 
      
      opacity: 1, // default: 1 
      
      //color: etro.parseColor('pink'), // default: new etro.Color(0, 0, 0, 1) randomColor({format: "rgba", alpha: 1}); 
      
      color: randomColor({format: "rgba", alpha: 1}), 
      
      font: '50px sans-serif', // default: '10px sans-serif' 
      
      textX: video[1]/2, // default: 0 
      
      textY: video[2] * 0.75, // default: 0 
      
      textAlign: 'center', // default: 'left' 
      
      textBaseline: 'alphabetic', // default: 'alphabetic' 
      
      textDirection: 'ltr', // default: 'ltr' 
      
      border: { // default: null (no border) 
        color: etro.parseColor('black'), 
        thickness: 10,
         
      }, 
      
      //background: etro.parseColor('red'), 
      
    });`

I tried doing it by adding the border, but I don't see any changes. Am I setting the border wrong?</div>

**Comment by FlandiaYingman** [comment]
@clabe45 
Are you currently working on it? If not, I am happy to deal with it.

**Comment by clabe45** [comment]
Thanks, sounds great
