### ISSUE TITLE
Url option for image, audio and video layers

### ISSUE THREAD

**Issue by clabe45** [etro-js/etro#61]
The user will be able to create a new layer from a local or remote path instead of providing an html element. The html element will be created by the layer.

- [x] `VisualSource#source` accepts strings
- [ ] `AudioSource#source` accepts strings

**Comment by pHoeniX-svg** [comment]
hello, what does the layer mean?

**Comment by clabe45** [comment]
Hey, thanks for asking! A layer is an image, audio clip, video clip, title, etc. Just a piece of content for the movie. The movie contains multiple layers and mixes them into one video that can be played or downloaded (with `Movie#play()` and `Movie#record()` respectively). [This page of the docs](https://clabe45.github.io/vidar/docs/overview) contains more info.
